# .github/workflows/release.yaml

on:
  release:
    types: [created]

jobs:
  release-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows
    env:
      CGO_ENABLED: 1
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1.28
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        project_path: "./cmd"
        binary_name: "ttt"
        extra_files: LICENSE README.md