# .github/workflows/release.yaml

on:
  release:
    types: [created]

jobs:
  # release-matrix:
  #   name: Release Go Binary
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       goos: [linux, windows, darwin]
  #       goarch: ["386", amd64, arm64]
  #       exclude:
  #         - goarch: "386"
  #           goos: darwin
  #         - goarch: arm64
  #           goos: windows
  #   env:
  #     CGO_ENABLED: 1
  #   steps:
  #   - uses: actions/checkout@v3
  #   - uses: wangyoucao577/go-release-action@v1.28
  #     with:
  #       github_token: ${{ secrets.GITHUB_TOKEN }}
  #       goos: ${{ matrix.goos }}
  #       goarch: ${{ matrix.goarch }}
  #       project_path: "./cmd"
  #       binary_name: "ttt"
  #       extra_files: LICENSE README.md

  build:
    name: "Build TTT (${{ matrix.target.os }}, ${{ matrix.go-version }})"
    runs-on: ${{ matrix.target.host || 'ubuntu-latest' }}
    env:
      GO111MODULE: on
      CGO_ENABLED: 1
    strategy:
      fail-fast: false
      matrix:
        # use max/min supported Go versions
        go-version: ["1.18.x"]
        target:
          - os: linux
          - os: windows
            ext: .exe
          - os: android
            args: -app-id calc.${GITHUB_SHA}
          - os: darwin
            args: -app-id calc.${GITHUB_SHA}
            host: macos-latest

    steps:
      - name: Setup Go environment
        id: setup-go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout fyne-cross
        uses: actions/checkout@v3
        with:
          repository: fyne-io/fyne-cross
          path: fyne-cross

      - name: Install Fyne-cross
        working-directory: fyne-cross
        run: go install

      - name: Install Fyne
        if: ${{ runner.os == 'macos' }}
        run: |
          go install fyne.io/fyne/v2/cmd/fyne@latest ||
          go get fyne.io/fyne/v2/cmd/fyne@latest

      - name: Install Podman
        if: ${{ runner.os == 'macos' }}
        run: |
          brew install podman
          podman machine init
          podman machine start
            
      - name: Build
        run: |
          fyne-cross \
            ${{ matrix.target.os }} \
            ${{ matrix.target.args }} \
            -debug -no-cache \
            -name ttt-${{ matrix.target.os }}${{ matrix.target.ext }} \
            ./cmd

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: fyne-cross/dist/${{ matrix.target.os }}-${{ matrix.target.arch }/