# .github/workflows/release.yaml

on:
  release:
    types: [created]

jobs:
  build:
    name: "Build TTT (${{ matrix.target.os }}, ${{ matrix.go-version }})"
    runs-on: ${{ matrix.target.host || 'ubuntu-latest' }}
    env:
      GO111MODULE: on
    strategy:
      fail-fast: false
      matrix:
        # use max/min supported Go versions
        go-version: 
          - 1.18.x
        target:
          - os: linux
            dir: linux-amd64
          - os: windows
            dir: windows-amd64
            ext: .exe
          - os: android
            args: -app-id calc.${GITHUB_SHA}
          # - os: darwin
          #   dir: darwin-amd64
          #   args: -app-id calc.${GITHUB_SHA}
          #   host: macos-latest
          - os: web
            dir: web-build

    steps:
      - name: Setup Go environment
        id: setup-go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache build artifacts
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/.cache/fyne-cross
          key: ${{ runner.os }}-build-cache-${{ hashFiles('**/go.sum') }}

      - name: Checkout fyne-cross
        uses: actions/checkout@v3
        with:
          repository: fyne-io/fyne-cross
          path: fyne-cross

      - name: Install Fyne-cross
        working-directory: fyne-cross
        run: go install

      - name: Install Fyne
        if: ${{ runner.os == 'macos' }}
        run: |
          go install fyne.io/fyne/v2/cmd/fyne@latest ||
          go get fyne.io/fyne/v2/cmd/fyne@latest

      - name: Install Podman
        if: ${{ runner.os == 'macos' }}
        run: |
          brew install podman
          podman machine init
          podman machine start
            
      - name: Build
        run: |
          fyne-cross \
            ${{ matrix.target.os }} \
            ${{ matrix.target.args }} \
            -debug -no-cache \
            -name ${{ matrix.target.os }}${{ matrix.target.ext }} \
            ./cmd

      - name: Archive web
        if: ${{ matrix.target.os == 'web' }}
        run: |
          mkdir fyne-cross/dist/web-build
          tar -czvf fyne-cross/dist/web-build/web.tar.gz -C fyne-cross/dist/web .

      - name: Upload Assets
        uses: AButler/upload-release-assets@v2.0
        with:
          files: fyne-cross/dist/${{ matrix.target.dir || matrix.target.os }}/*
          repo-token: ${{ secrets.GITHUB_TOKEN }}